apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  annotations:
    workflows.argoproj.io/description: Hello world example.
    workflows.argoproj.io/tags: example
    workflows.argoproj.io/version: '>= 2.9.0'
  name: hello-world
spec:
  entrypoint: argosay
  templates:
  - container:
      args:
      - echo
      - hello argo!
      command:
      - /argosay
      image: argoproj/argosay:v2
      name: main
    name: argosay
